schema: 1
type: policy-context

id: api-gateway-does-not-match-endpoint-type-config
name: API gateway does not match endpoint type configuration
labels:
  - contextualization

csp: aws
service: apiGateway
resource-type: RestApis

class: risk
subclass: config
category: uncategorized
subcategory: best-practice

filters:
  - vendor: aws-config
    policies:
      - api-gw-endpoint-type-check
    match-type: any
    rules:
      - .vendorId == "aws-config" and (.vendorPolicy |contains ("api-gw-endpoint-type-check"))

risk-config:
  default-risk: ""
