micronaut:
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedMethods:
            - POST
            - PUT
            - GET
            - OPTIONS
            - DELETE
          maxAge: 3600

          exposedHeaders:
            - x-workflow-is-default
            - Content-Type
            - x-api-key
            - x-dassana-cache

  application:
    name: engine
  jms:
    sqs:
      enabled: true
env:
  dassanaBucket: ${dassanaBucket}
  dassanaDeadLetterQueue: ${dassanaDeadLetterQueue}
  dassanaEventBridgeBusName: ${dassanaEventBridgeBusName}
  dassanaStackName: ${DASSANA_STACK_NAME}
  dassanaCrossAccountRoleName: ${dassanaCrossAccountRoleName:""}
