schema: 1
type: policy-context

id: cloudwatch-alarm-does-not-have-specified-settings
name: CloudWatch alarm does not have specified settings
labels:
  - contextualization

csp: aws
service: cloudwatch
resource-type: alarm

class: risk
subclass: config
category: uncategorized
subcategory: best-practice

filters:
  - vendor: aws-config
    policies:
      - cloudwatch-alarm-settings-check
    match-type: any
    rules:
      - .vendorId == "aws-config" and (.vendorPolicy |contains ("cloudwatch-alarm-settings-check"))

risk-config:
  default-risk: ""
