schema: 1
type: policy-context
 
id: aws-config-must-record-all-possible-resources
name: AWS Config must record all possible resources
labels:
  - contextualization
 
csp: aws
service: config
resource-type: ConfigurationAggregator
 
class: risk
subclass: config
category: visibility
subcategory: hygiene
 
filters:
  - vendor: prisma-cloud
    policies:
      - 4c64a4d6-1b96-4004-8a11-f215aa8ee3ce
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "4c64a4d6-1b96-4004-8a11-f215aa8ee3ce"
 
risk-config:
  default-risk: medium
