schema: 1
type: policy-context

id: config-not-recording-all-resources
name: Config not recording all resources
labels:
  - contextualization

csp: aws
service: config
resource-type: ConfigurationAggregator

class: risk
subclass: config
category: visibility
subcategory: hygiene

filters:
  - vendor: prisma-cloud
    policies:
      - 4c64a4d6-1b96-4004-8a11-f215aa8ee3ce
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "4c64a4d6-1b96-4004-8a11-f215aa8ee3ce"

risk-config:
  default-risk: medium
