schema: 1.0
labels:
  - contextualization
type: contextualize
category: access-sharing
subcategory: public-access
id: "root-object-is-not-configured"
name: "CloudFront distribution is not configured to return default root object"

risk-config:
  default-risk: critical

filter:
  vendors:
    - name: security-hub
      policies:
        - "cloudfront-default-root-object-configured"
      match-type: any
      rules:

        - .workflowId == "security-hub" and (.vendorPolicy |contains ("cloudfront-default-root-object-configured") )