schema: 1
type: policy-context
 
id: aws-ec2-instance-not-configured-with-instance-metadata-service-v2-(imdsv2)
name: AWS EC2 instance not configured with Instance Metadata Service v2 (IMDSv2)
labels:
  - contextualization
 
csp: aws
service: ec2
resource-type: instance
 
class: risk
subclass: config
category: iam
subcategory: authentication
 
filters:
  - vendor: prisma-cloud
    policies:
      - 32f75d19-c34d-4ec5-aa8c-675959db3aad
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "32f75d19-c34d-4ec5-aa8c-675959db3aad"
 
risk-config:
  default-risk: medium
