schema: 1
type: policy-context

id: managedinstance-is-running-blacklisted-application
name: Specified blacklisted applications are installed on the instance
labels:
  - contextualization

csp: aws
service: ec2
resource-type: instance

class: risk
subclass: config
category: uncategorized
subcategory: best-practice

filters:
  - vendor: aws-config
    policies:
      - ec2-managedinstance-applications-blacklisted
    match-type: any
    rules:
      - .vendorId == "aws-config" and (.vendorPolicy |contains ("ec2-managedinstance-applications-blacklisted"))

risk-config:
  default-risk: ""
